### ISSUE TITLE
Add support for Debian 

### ISSUE THREAD

**Issue by devonharless** [jonhadfield/puppet-wordpress#1]
[app.pp]
$apache, $phpmysql, $php variables receive incorrect defaults when running on Debian. Correct values are apache2, php5-mysql, and php5, respectively.

[db.pp]
$mysqlclient, $mysqlservice variables also receive incorrect defaults when running on Debian. Correct values are mysql-client, and mysql.

**Comment by jonhadfield** [comment]
Added debian support as specified.
