### ISSUE TITLE
Depracted warnings

### ISSUE THREAD

**Issue by hbokh** [jonhadfield/puppet-wordpress#2]
Multiple deprecated warnings for "$db_*"-entries in the files wp-config.erb and create_wordpress_db.erb.
Example:

`warning: Dynamic lookup of $db_name ... wp-config.erb:19 is deprecated. For more information, see` `http://docs.puppetlabs.com/guides/scope_and_puppet.html. To see the change in behavior,`
`use the --debug flag.`

**Comment by jonhadfield** [comment]
Changed templates to use instance variables as recommended: http://docs.puppetlabs.com/guides/templating.html.
